name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        🐞 **Thank you for reporting a bug!** Please provide as much detail as possible to help us resolve it quickly.
  - type: input
    id: contact
    attributes:
      label: Contact Details (Optional)
      description: If we need more information, how can we reach you?
      placeholder: Your email or GitHub username
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: Describe the bug. Include what you expected to happen and what actually happened. Attach screenshots if possible.
      placeholder: Detailed description of the bug
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of the project are you using?
      options:
        - 1.0.0-alpha
        - 1.0.0
        - 1.0.1 
        - 2.0.0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Affected Browsers
      description: Which browsers are affected by this bug?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Mentor404/anilist-css/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
