name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        💡 **Thanks for suggesting a feature!** Please provide a clear and concise description of what you would like to see.
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: What feature do you want to add? How would it benefit the project?
      placeholder: Describe the feature you're suggesting
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Add any other context, links, or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Mentor404/anilist-css/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
